### PR TITLE
fix(git): try to fix CODEOWNERS syntax

### PR DESCRIPTION
**Pull request by jonaseberle**
This does not seem to have worked before. It never added me, just Dave.

### CODE REVIEW

**Comment by jonaseberle** [comment]
@davereid could you give feedback if you are ok with this change?

**Comment by tyler36** [comment]
Just a friendly ping

ping @davereid 
ping @davereid-pfg (not sure if same person)

**Review by rfay — APPROVED** [review]
This is fine, just go ahead with it. Sometimes it's hard to get Dave.

**Comment by rfay** [comment]
Rebased.

**Comment by rfay** [comment]
Note that ubuntu-20.04 is going away, best to update these tests to 22.04 and 24.04 perhaps.  ubuntu-latest is about to become ubuntu-24.04 as well.

**Pull request merged**
